export const dataBestSeller=[
    {
        id:1,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p10.jpg"
    },
    {
        id:2,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p14.jpg"
    },
    {
        id:3,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p17.jfif"
    },
    {
        id:4,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p11.jpg"
    },
    {
        id:5,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p12.jfif"
    },
    {
        id:6,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p21.jpg"
    },
    {
        id:7,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p15.jfif"
    },
    {
        id:8,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/p16.jfif"
    },
]